# Generated by Django 5.2.8 on 2025-12-24 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0003_productcard'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductCard',
        ),
    ]
