# Generated by Django 5.2.8 on 2025-12-29 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0005_contactmessage_purchasehistory_userdetails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetails',
            old_name='address_line_1',
            new_name='address_line',
        ),
        migrations.AddField(
            model_name='userdetails',
            name='user_full_name',
            field=models.CharField(default='User', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='mobile_number',
            field=models.CharField(max_length=20),
        ),
    ]
